#!/usr/bin/env python3
"""
STAC-BUILD: Setup initial personnel folders, profiles, and team1.
Run once to bootstrap file-based persistence for existing users.
Hernán Barreto — Ingerop IN3
"""

import asyncio
import sys
import os

# Add server dir to path
sys.path.insert(0, os.path.dirname(__file__))

from db import async_session_factory, init_db, User
from db_team import Team, TeamMember, SessionAssignment
from sqlalchemy import select
from activity_logger import (
    save_user_profile, _append_user_log, save_team_file,
    log_to_team, update_user_teams,
)
from datetime import datetime


async def _get_user_team_ids_local(session, user_id: int) -> list:
    """Get team IDs a user belongs to (member or manager)."""
    member_q = await session.execute(
        select(TeamMember.team_id).where(TeamMember.user_id == user_id)
    )
    managed_q = await session.execute(
        select(Team.id).where(Team.manager_id == user_id)
    )
    ids = set(r[0] for r in member_q.all()) | set(r[0] for r in managed_q.all())
    return sorted(ids)


async def main():
    print("═══ STAC-BUILD: Initial Data Setup ═══\n")

    # Initialize DB
    await init_db()

    async with async_session_factory() as session:
        # ── 1. Get all existing users ──
        result = await session.execute(select(User).order_by(User.id))
        users = result.scalars().all()

        if not users:
            print("❌ No users found. Create users first via the Admin panel.")
            return

        print(f"Found {len(users)} users:")
        for u in users:
            print(f"  {u.id}. {u.username} ({u.role})")

        # ── 2. Create personnel folders + profile.json for each user ──
        print("\n── Creating personnel folders & profiles ──")
        for u in users:
            user_dict = u.to_dict()
            save_user_profile(user_dict, teams=[])
            _append_user_log(u.username, "system_init",
                detail="Personnel folder initialized by setup script")
            print(f"  ✅ personnel/{u.username}/profile.json")

        # ── 3. Create team1 ──
        print("\n── Creating team 'team1' ──")

        # Check if team already exists
        existing_team = await session.execute(
            select(Team).where(Team.name == "team1")
        )
        team = existing_team.scalar_one_or_none()

        if team:
            print(f"  ⚠️  Team 'team1' already exists (id={team.id}), regenerating files...")

            # Get manager
            manager_user = await session.get(User, team.manager_id)

            # Build and persist team file
            members_q = await session.execute(
                select(TeamMember, User).join(User, TeamMember.user_id == User.id).where(
                    TeamMember.team_id == team.id
                )
            )
            members = []
            for tm, user in members_q.all():
                members.append({
                    "user_id": user.id,
                    "username": user.username,
                    "full_name": user.full_name,
                    "role": user.role,
                    "added_at": tm.joined_at.isoformat() + "Z" if tm.joined_at else None,
                })

            sessions_q = await session.execute(
                select(SessionAssignment).where(SessionAssignment.team_id == team.id)
            )
            session_ids = [sa.session_id for sa in sessions_q.scalars().all()]

            snapshot = {
                "id": team.id,
                "name": team.name,
                "description": team.description,
                "is_active": team.is_active,
                "manager": {"id": team.manager_id, "username": manager_user.username if manager_user else "unknown"},
                "members": members,
                "sessions": session_ids,
            }
            save_team_file(snapshot)
            print(f"  ✅ teams/{team.id}_team1/team.json")

            log_to_team(team.id, team.name, "files_regenerated",
                actor="admin", detail="Team files regenerated by setup script")

            # Update member profiles with team id
            for u in users:
                if u.role == "admin":
                    update_user_teams(u.username, [])
                else:
                    user_teams = await _get_user_team_ids_local(session, u.id)
                    update_user_teams(u.username, user_teams)
            print(f"  ✅ Updated member profiles with team assignments")
        else:
            # Find the manager user
            manager_user = None
            for u in users:
                if u.role == "manager":
                    manager_user = u
                    break

            if not manager_user:
                print("  ❌ No user with role 'manager' found. Cannot assign PM.")
                return

            # Create team
            team = Team(
                name="team1",
                description="Primary project team",
                manager_id=manager_user.id,
            )
            session.add(team)
            await session.commit()
            await session.refresh(team)
            print(f"  ✅ Created team 'team1' (id={team.id}) with PM: {manager_user.username}")

            # Add manager as member
            session.add(TeamMember(
                team_id=team.id,
                user_id=manager_user.id,
                added_by=1,  # admin
            ))
            await session.commit()

            # Add all non-admin users as members
            for u in users:
                if u.role == "admin":
                    continue
                if u.id == manager_user.id:
                    continue  # already added

                session.add(TeamMember(
                    team_id=team.id,
                    user_id=u.id,
                    added_by=1,  # admin
                ))
                print(f"  ✅ Added {u.username} ({u.role}) to team1")

            await session.commit()

            # ── 4. Persist team file ──
            members_q = await session.execute(
                select(TeamMember, User).join(User, TeamMember.user_id == User.id).where(
                    TeamMember.team_id == team.id
                )
            )
            members = []
            for tm, user in members_q.all():
                members.append({
                    "user_id": user.id,
                    "username": user.username,
                    "full_name": user.full_name,
                    "role": user.role,
                    "added_at": tm.joined_at.isoformat() + "Z" if tm.joined_at else None,
                })

            snapshot = {
                "id": team.id,
                "name": team.name,
                "description": team.description,
                "is_active": True,
                "manager": {"id": manager_user.id, "username": manager_user.username},
                "members": members,
                "sessions": [],
            }
            save_team_file(snapshot)
            print(f"  ✅ teams/{team.id}_team1/team.json")

            # ── 5. Log team creation ──
            log_to_team(team.id, team.name, "team_created",
                actor="admin", detail=f"Team created by setup script with PM {manager_user.username}")

            # ── 6. Update all member profiles with team id ──
            for u in users:
                if u.role == "admin":
                    update_user_teams(u.username, [])  # admin not in team
                else:
                    update_user_teams(u.username, [team.id])
                    _append_user_log(u.username, "added_to_team",
                        team_id=team.id, detail=f"Added to team 'team1' by setup script")

            # Admin log
            _append_user_log("admin", "team_created",
                team_id=team.id, detail=f"Created team 'team1' with PM {manager_user.username} via setup script")

    print("\n═══ Setup complete! ═══")
    print("Personnel folders: server/personnel/")
    print("Team files: server/teams/")


if __name__ == "__main__":
    asyncio.run(main())
